### ISSUE TITLE
Handling of log messages should also log to stderr when appropriate

### ISSUE THREAD

**Issue by oleavr** [frida/frida-node#21]
We should refine this:
https://github.com/frida/frida-node/blob/095bdda90061b93f97e85bf8479ad526854af152/lib/script.js#L113

**Comment by juliangruber** [comment]
when would it be appropriate?

**Comment by oleavr** [comment]
@juliangruber It should be based on the `level` field:

https://github.com/frida/frida-gum/blob/26c0dc3edfc61598dc72c7640be86c8d748afe2f/bindings/gumjs/gumjs-core.js#L80-102
