### ISSUE TITLE
Official TypeScript support

### ISSUE THREAD

**Issue by farism** [frida/frida-node#24]
I came across a project for adding definitions for TypeScript [here](https://github.com/frida-spectre/typed-frida). However, I'm not sure if/how much it's out of date, and it also isn't published under the npm `@types` org so consuming the definitions is not the most straightforward thing. Has there been any discussion around adding official typings or - perhaps eventually - even a typescript rewrite?

**Comment by ChiChou** [comment]
Are you looking for this?
https://github.com/frida/frida-gum/tree/master/bindings/gumjs/types

**Comment by oleavr** [comment]
At some point it would be nice to rewrite frida-node (this module) in TypeScript. I think @farism was referring to the GumJS side of things, though, so that means this issue can be closed — we have this now.

**Comment by zixia** [comment]
rewrite frida-node in TypeScript +1
