### ISSUE TITLE
high resolution timer support

### ISSUE THREAD

**Issue by dweinstein** [frida/frida-node#27]
I might have missed an alternative, but I was hoping to find something to provide higher resolution timers than what we get from `Date.now()`. Should we consider having [`process.hrtime()`](https://nodejs.org/api/process.html#process_process_hrtime_time) perhaps?

**Comment by oleavr** [comment]
Definitely! We'll get support for this once frida/frida-gum#198 lands, along with the other sampler implementations (like for CPU clock cycles) provided by [gum-prof](https://github.com/frida/frida-gum/tree/master/libs/gum/prof).

**Comment by oleavr** [comment]
Let's keep tracking this in frida/frida-gum#198.
