### ISSUE TITLE
Prebuilt binaries for node v13.x?

### ISSUE THREAD

**Issue by dogtopus** [frida/frida-node#45]
Currently attempting to install frida on node v13.x will fail with error indicating that no prebuilt binaries was found.

**Comment by oleavr** [comment]
This is blocked on support for it in [node-abi](https://github.com/lgeiger/node-abi). Would you be interested in opening a PR there? Should only be a matter of adding it to the list in `index.js`.

**Comment by gebing** [comment]
@oleavr 
[node-abi](https://github.com/lgeiger/node-abi) already support node 13, but `frida-node` still install failed. My node version is `13.1.0`?

**Comment by oleavr** [comment]
@gebing Yay! We now only need to delete the lock-file and add the version to the list in `releng/release.py`. Will do it on the next release, most likely tomorrow.
