### ISSUE TITLE
Frida hook to locally running Node server

### ISSUE THREAD

**Issue by Mihirmathur** [frida/frida-node#49]
I'm trying to hook up Frida to a Node server using the CLI. I'm able to connect to the Node process but unable to hook to functions I've defined in the server
The command I'm using is `frida-trace -i 'helloworld' <node-pid>` and it returns "Started tracing 0 functions" even though the Node server has the helloworld function. 

I'm new to Frida so might be doing something wrong. What is the best way to trace functions running on a Node server with Frida?

**Comment by oleavr** [comment]
Hey,

frida-trace does not support tracing Node.js (yet). (PRs welcome though!)

Cheers!
