### ISSUE TITLE
node-mac target fails trying to execute /npm if node is not installed

### ISSUE THREAD

**Issue by radare** [frida/frida-node#5]
...
&& mv ../build/frida_stripped-mac-x86_64/lib/node_modules/frida.tmp ../build/frida_stripped-mac-x86_64/lib/node_modules/frida
/bin/sh: /npm: No such file or directory
make[1]: *** [build/frida_stripped-mac-x86_64/lib/node_modules/frida] Error 127
```

**Comment by radare** [comment]
This can be solved by adding a dependency make target that runs `npm --version`

**Comment by oleavr** [comment]
Thanks! Fixed:
https://github.com/frida/frida/commit/a1a965a0a33613330506e77ed96a7ee9fca46c94
