### ISSUE TITLE
NativeCallback type in @types/frida-gum is outdated (and maybe some other classes too)

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [frida/frida-node#52]
In the docs, the NativeCallback class has the constructor like this:
```js
new NativeCallback(func, returnType, argTypes[, abi])
```
But its type definition in @types/frida-gum is:
```ts
declare class NativeCallback extends NativePointer {
    constructor(func: NativeCallbackImplementation, retType: NativeType, argTypes: NativeType[]);
}
```
Can you update the type definition for NativeCallback?

**Comment by oleavr** [comment]
Thanks, great catch! I've included the fix in my pending [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45592).
