### ISSUE TITLE
Correct way to get args in onLeave?

### ISSUE THREAD

**Issue by CaledoniaProject** [frida/frida-node#65]
The testMethod has a pointer argument which will be modified in the method. I need to read its value in onLeave. Right now I had to store the variable in onEnter then read it in onLeave.

I'm wondering if there's a better way to do that? It's not healthy for multithread programs.

```
    let data = null
    Interceptor.attach(testMethod, {
        onEnter: function (args) {
            data = args[4]
        },
        onLeave: function (retval) {
            console.log(Memory.readInt(data))           
        }
    });
```

**Comment by FrenchYeti** [comment]
Hi,

Simple by doing :
```
Interceptor.attach(testMethod, {
onEnter: function (args) {
this.data = args[4];
}, onLeave: function (retval){
console.log(Memory.readInt(this.data))
}
});
```

You can also use CPU context to save the value of 4th arg (example with arm64):

```
this.data = this.context.x4;
```

-------- Message d'origine --------

**Comment by oleavr** [comment]
Also some useful hints [here](https://frida.re/docs/best-practices/).

**Comment by CaledoniaProject** [comment]
Thanks!
