### ISSUE TITLE
Block calls to original method conditionally

### ISSUE THREAD

**Issue by CaledoniaProject** [frida/frida-node#66]
I'm trying to block calls to original method in onEnter(), something like

```
onEnter: (args) => {
  originalMethod = this.XXX

  if (condition) {
      this.originalMethod(args)
  } else {
      return retVal
  }
}
```

Is it supported by frida?

**Comment by oleavr** [comment]
Yes, use `Interceptor.replace()`.

**Comment by CaledoniaProject** [comment]
Thanks, I've found an example here:
https://gist.github.com/n30m1nd/a926931a009e09236b07d7238670ad0a
