### ISSUE TITLE
Port over to using NAN

### ISSUE THREAD

**Issue by SomeoneWeird** [frida/frida-node#7]
Discussed on IRC, porting over to [NAN](https://github.com/nodejs/nan) will allow us to support future breaking V8 changes, and iojs immediately.

**Comment by SomeoneWeird** [comment]
Started [here](https://github.com/SomeoneWeird/frida-node/tree/nan)

**Comment by oleavr** [comment]
Awesome work! :heart:

**Comment by SomeoneWeird** [comment]
Branch now compiles with latest iojs (v2.5.0)
