### ISSUE TITLE
RPC function never resolved in jest

### ISSUE THREAD

**Issue by ZachQin** [frida/frida-node#80]
When call rpc function in jest, the promise will never resolve.
Finally found the cause of the problem:
https://github.com/facebook/jest/issues/2549
`payload instanceof Array` in `isRpcSendMessage` function returns `false`, because the payload is not created as the same context as jest. The problem can be solved by using `Array.isArray(payload)` instead.

**Comment by leonitousconforti** [comment]
Thanks @ZachQin! I can confirm that I was having the exact same problem and this solution worked for me, would be great to get your changes merged in

**Comment by ZachQin** [comment]
> Thanks @ZachQin! I can confirm that I was having the exact same problem and this solution worked for me, would be great to get your changes merged in

Hi @leonitousconforti , I'm glad to hear that the solution worked for you! The changes have indeed been merged. Thanks for your feedback and support!
